import type { Race } from "@/lib/races";
import { getRaceById } from "@/lib/races";
import type { PlannedSession, WeekPlan } from "@/lib/plan-generator";
import type { PlanPhase } from "@/types/database";
import type { PreviewInput, PreviewResult } from "./preview-plan";
import { daysUntil } from "./race-meta";

/* ============================================================================
   IN-APP DEMO DATA — shared across every v2 in-app surface (home, plan, session,
   progress, races, coach, profile).
   ----------------------------------------------------------------------------
   The PLAN itself is generated by Parrot's REAL engine and run through the REAL
   validation layer (generateValidatedPlan → generatePlan + validatePlanProgression).
   Generation happens SERVER-SIDE in app/layout.tsx; the validated plan is mapped
   here via buildAppPlan() and handed to the surfaces through React context
   (see app-data.tsx). Only the *training-history* series the engine doesn't
   produce — CTL/ATL/TSB, actual intensity split, threshold history, adherence —
   are fabricated, and every one of those is flagged `mock: true` in the UI.
   ============================================================================ */

/** The athlete we simulate. A flagship city marathon gives a full ~24-week plan
 *  with every phase visible. Swap freely — all surfaces follow this one source. */
const DEMO_RACE_ID = "stockholm-marathon";

const DEMO_INPUT = {
  experience: "intermediate" as const,
  daysPerWeek: 5,
  weeklyKm: 42,
  longRunDay: 0, // Sunday
};

const DEMO_ATHLETE = { name: "Alex", experience: DEMO_INPUT.experience };

/** Resolves the demo onboarding input (race + profile) used to seed the in-app
 *  preview. Returns null if the demo race id can't be resolved. */
export function buildDemoPreviewInput(): PreviewInput | null {
  const race = getRaceById(DEMO_RACE_ID);
  if (!race) return null;
  return { race, ...DEMO_INPUT };
}

export interface AppSession extends PlannedSession {
  id: string;
  date: Date;
  weekNumber: number;
  phase: PlanPhase;
  isRecovery: boolean;
}

export interface AppWeek extends WeekPlan {
  weekStart: Date;
  weekEnd: Date;
  appSessions: AppSession[];
}

export interface AppPlan {
  race: Race;
  preview: PreviewResult;
  weeks: AppWeek[];
  raceDate: Date;
  planWeeks: number;
  thresholdPaceLabel: string;
  athlete: { name: string; experience: string };
}

/* ── date helpers (local, TZ-safe parse of 'yyyy-MM-dd') ──────────────────── */

function parseISODate(s: string): Date {
  const [y, m, d] = s.split("-").map(Number);
  return new Date(y, m - 1, d);
}
function addDays(d: Date, n: number): Date {
  const r = new Date(d);
  r.setDate(r.getDate() + n);
  return r;
}
/** dayOfWeek: 0=Sun..6=Sat. Weeks start Monday (weekStartsOn:1 in the engine). */
function offsetFromMonday(dayOfWeek: number): number {
  return dayOfWeek === 0 ? 6 : dayOfWeek - 1;
}

/* ── map a validated PreviewResult into the in-app AppPlan shape ───────────── */

export function buildAppPlan(
  result: PreviewResult,
  race: Race,
  athlete: { name: string; experience: string } = DEMO_ATHLETE,
): AppPlan {
  const weeks: AppWeek[] = result.weeks.map((w) => {
    const weekStart = parseISODate(w.startsOn);
    const weekEnd = addDays(weekStart, 6);
    const appSessions: AppSession[] = w.sessions.map((s) => ({
      ...s,
      id: `${w.weekNumber}-${s.dayOfWeek}-${s.orderInDay}`,
      date: addDays(weekStart, offsetFromMonday(s.dayOfWeek)),
      weekNumber: w.weekNumber,
      phase: w.phase,
      isRecovery: w.isRecovery,
    }));
    return { ...w, weekStart, weekEnd, appSessions };
  });

  return {
    race,
    preview: result,
    weeks,
    raceDate: result.raceDate,
    planWeeks: result.planWeeks,
    thresholdPaceLabel: result.thresholdPaceLabel,
    athlete,
  };
}

/* ── pure selectors over a provided AppPlan ───────────────────────────────── */

export function getAllSessions(plan: AppPlan): AppSession[] {
  return plan.weeks.flatMap((w) => w.appSessions);
}

export function getSessionById(
  plan: AppPlan,
  id: string,
): { session: AppSession; week: AppWeek } | null {
  for (const week of plan.weeks) {
    const session = week.appSessions.find((s) => s.id === id);
    if (session) return { session, week };
  }
  return null;
}

/** First session today or later (training types only — skips rest days). */
export function getNextSession(plan: AppPlan, from: Date = new Date()): AppSession | null {
  const start = new Date(from.getFullYear(), from.getMonth(), from.getDate());
  const upcoming = getAllSessions(plan)
    .filter((s) => s.type !== "rest" && s.date >= start)
    .sort((a, b) => a.date.getTime() - b.date.getTime());
  return upcoming[0] ?? null;
}

/** The week containing `from`, falling back to the first week. */
export function getCurrentWeek(plan: AppPlan, from: Date = new Date()): AppWeek {
  const hit = plan.weeks.find((w) => from >= w.weekStart && from <= addDays(w.weekEnd, 0.999));
  return hit ?? plan.weeks[0];
}

export function daysToRace(plan: AppPlan, from: Date = new Date()): number {
  return daysUntil(plan.raceDate, from);
}

/* ============================================================================
   MOCK TRAINING HISTORY  (flagged everywhere it surfaces)
   ============================================================================ */

/** Deterministic pseudo-random so charts are stable between renders/builds. */
function seeded(seed: number): () => number {
  let s = seed % 2147483647;
  if (s <= 0) s += 2147483646;
  return () => (s = (s * 16807) % 2147483647) / 2147483647;
}

export interface FitnessPoint {
  weekLabel: string;
  ctl: number; // fitness (chronic load)
  atl: number; // fatigue (acute load)
  tsb: number; // form (CTL − ATL)
}

/** 12 weeks of CTL/ATL/TSB trending into today. MOCK. */
export const fitnessTrend: { mock: true; points: FitnessPoint[] } = (() => {
  const rnd = seeded(73);
  const points: FitnessPoint[] = [];
  let ctl = 34;
  for (let i = 11; i >= 0; i--) {
    const ramp = (11 - i) * 2.1;
    ctl = 34 + ramp + (rnd() - 0.5) * 2;
    const atl = ctl + (rnd() - 0.35) * 14;
    points.push({
      weekLabel: `−${i}v`,
      ctl: Math.round(ctl),
      atl: Math.round(atl),
      tsb: Math.round(ctl - atl),
    });
  }
  return { mock: true, points };
})();

export interface IntensityBucket {
  key: "easy" | "moderate" | "hard";
  actual: number; // %
  target: number; // %
}

/** Actual vs target intensity distribution (polarized 80/20 model). MOCK actual. */
export const intensityDistribution: { mock: true; buckets: IntensityBucket[] } = {
  mock: true,
  buckets: [
    { key: "easy", actual: 73, target: 80 },
    { key: "moderate", actual: 19, target: 12 },
    { key: "hard", actual: 8, target: 8 },
  ],
};

export interface ThresholdPoint {
  monthLabelSv: string;
  monthLabelEn: string;
  secPerKm: number;
}

/** Threshold-pace history improving over the block. MOCK. */
export const thresholdHistory: { mock: true; points: ThresholdPoint[] } = {
  mock: true,
  points: [
    { monthLabelSv: "jan", monthLabelEn: "Jan", secPerKm: 330 }, // 5:30
    { monthLabelSv: "feb", monthLabelEn: "Feb", secPerKm: 324 },
    { monthLabelSv: "mar", monthLabelEn: "Mar", secPerKm: 318 },
    { monthLabelSv: "apr", monthLabelEn: "Apr", secPerKm: 313 },
    { monthLabelSv: "maj", monthLabelEn: "May", secPerKm: 308 }, // 5:08
    { monthLabelSv: "jun", monthLabelEn: "Jun", secPerKm: 305 }, // 5:05
  ],
};

export interface AdherenceWeek {
  weekLabel: string;
  planned: number;
  completed: number;
}

/** Session-completion adherence over recent weeks. MOCK. */
export const adherence: {
  mock: true;
  weeks: AdherenceWeek[];
  overallPct: number;
  streak: number;
} = (() => {
  const weeks: AdherenceWeek[] = [
    { weekLabel: "−5v", planned: 5, completed: 5 },
    { weekLabel: "−4v", planned: 5, completed: 4 },
    { weekLabel: "−3v", planned: 6, completed: 6 },
    { weekLabel: "−2v", planned: 5, completed: 5 },
    { weekLabel: "−1v", planned: 6, completed: 5 },
    { weekLabel: "nu", planned: 5, completed: 3 },
  ];
  const planned = weeks.reduce((n, w) => n + w.planned, 0);
  const completed = weeks.reduce((n, w) => n + w.completed, 0);
  return { mock: true, weeks, overallPct: Math.round((completed / planned) * 100), streak: 9 };
})();

/** Format seconds/km as m:ss. */
export function fmtPaceSec(sec: number): string {
  const m = Math.floor(sec / 60);
  const s = Math.round(sec % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}
